# Generated by Django 5.0.4 on 2024-04-12 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiclecondition', '0024_alter_carreceivingvcmodel_receiving_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarExpensesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('REFUELING COST', 'Refueling Cost'), ('WASHING COST', 'Washing Cost')], max_length=14, verbose_name='Expense Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Amount')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('payment_method', models.CharField(choices=[('MASTER CARD', 'Master Card'), ('REFUELING CARD', 'Refueling Card'), ('PRIVATELY PAID', 'Privately Paid')], max_length=14, verbose_name='Payment Method')),
                ('receipt_image', models.ImageField(upload_to='workorder/%Y-%m-%d-%H-%M-%S/', verbose_name='Receipt Image')),
            ],
        ),
        migrations.CreateModel(
            name='OverheadExpensesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('TRAIN TICKET COST', 'Train Ticket Cost'), ('TRAM TICKET COST', 'Tram Ticket Cost'), ('BUS TICKET COST', 'BUS Ticket Cost'), ('TAXI COST', 'Taxi Cost')], max_length=17, verbose_name='Expense Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Amount')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('payment_method', models.CharField(choices=[('MASTER CARD', 'Master Card'), ('REFUELING CARD', 'Refueling Card'), ('PRIVATELY PAID', 'Privately Paid')], max_length=14, verbose_name='Payment Method')),
                ('receipt_image', models.ImageField(upload_to='workorder/%Y-%m-%d-%H-%M-%S/', verbose_name='Receipt Image')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.IntegerField(editable=False, unique=True, verbose_name='Work Order Number')),
                ('type', models.CharField(choices=[('CAR DELIVERY', 'Car Delivery'), ('CAR RETURN', 'Car Return'), ('PUD PICKUP', 'PUD Pickup'), ('PUD DROP', 'PUD Drop')], default='CAR DELIVERY', max_length=12, verbose_name='Work Order Type')),
                ('car', models.CharField(max_length=50, verbose_name='Car')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DENIED', 'Denied'), ('ACCEPTED', 'Accepted'), ('CAR PREPARING', 'Car Preparing'), ('OUT FOR DELIVERY', 'Out For Delivery'), ('DELIVERY SUCCESSFUL', 'Delivery Successful'), ('DELIVERY UNSUCCESSFUL', 'Delivery Unsuccessful')], default='PENDING', max_length=21, verbose_name='Work Order Status')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery Date')),
                ('car_dealer', models.CharField(max_length=50, verbose_name='Car Dealer')),
                ('customer', models.CharField(max_length=100, verbose_name='Customer')),
                ('delivery_agent', models.CharField(max_length=50, verbose_name='Delivery Agent')),
                ('car_delivering_vc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiclecondition.cargivingvcmodel', verbose_name='Car Delivering VC')),
                ('car_expenses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorder.carexpensesmodel', verbose_name='Car Expenses')),
                ('car_receiving_vc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiclecondition.carreceivingvcmodel', verbose_name='Car Receiving VC')),
                ('overhead_expenses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorder.overheadexpensesmodel', verbose_name='Overhead Expenses')),
            ],
        ),
    ]
