# Generated by Django 5.0.4 on 2024-04-26 12:46

import django.db.models.deletion
import workorder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        ('cardealer', '0001_initial'),
        ('customer', '0001_initial'),
        ('deliveryagent', '0001_initial'),
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarExpensesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('REFUELING COST', 'Refueling Cost'), ('WASHING COST', 'Washing Cost')], max_length=14, verbose_name='Expense Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Amount')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('payment_method', models.CharField(choices=[('MASTER CARD', 'Master Card'), ('REFUELING CARD', 'Refueling Card'), ('PRIVATELY PAID', 'Privately Paid')], max_length=14, verbose_name='Payment Method')),
                ('receipt_image', models.ImageField(upload_to=workorder.models.this_wo_ce_folder_path, verbose_name='Receipt Image')),
            ],
        ),
        migrations.CreateModel(
            name='OverheadExpensesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('TRAIN TICKET COST', 'Train Ticket Cost'), ('TRAM TICKET COST', 'Tram Ticket Cost'), ('BUS TICKET COST', 'BUS Ticket Cost'), ('TAXI COST', 'Taxi Cost')], max_length=17, verbose_name='Expense Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Amount')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('payment_method', models.CharField(choices=[('MASTER CARD', 'Master Card'), ('REFUELING CARD', 'Refueling Card'), ('PRIVATELY PAID', 'Privately Paid')], max_length=14, verbose_name='Payment Method')),
                ('receipt_image', models.ImageField(upload_to=workorder.models.this_wo_oe_folder_path, verbose_name='Receipt Image')),
            ],
        ),
        migrations.CreateModel(
            name='ProofImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_number_image', models.ImageField(upload_to=workorder.models.this_wo_vc_folder_path, verbose_name='VIN Image')),
                ('license_plate_image', models.ImageField(upload_to=workorder.models.this_wo_vc_folder_path, verbose_name='License Plate Image')),
                ('emission_sticker_image', models.ImageField(upload_to=workorder.models.this_wo_vc_folder_path, verbose_name='Emission Sticker Image')),
                ('registration_certificate_image', models.ImageField(upload_to=workorder.models.this_wo_vc_folder_path, verbose_name='Registration Certificate Image')),
                ('dashboard_image', models.ImageField(upload_to=workorder.models.this_wo_vc_folder_path, verbose_name='Dashboard Image')),
                ('front_image', models.ImageField(upload_to=workorder.models.this_wo_vc_folder_path, verbose_name='Front Image')),
                ('left_front_image', models.ImageField(upload_to=workorder.models.this_wo_vc_folder_path, verbose_name='Left Front Image')),
                ('left_rear_image', models.ImageField(upload_to=workorder.models.this_wo_vc_folder_path, verbose_name='Left Rear Image')),
                ('rear_image', models.ImageField(upload_to=workorder.models.this_wo_vc_folder_path, verbose_name='Rear Image')),
                ('right_rear_image', models.ImageField(upload_to=workorder.models.this_wo_vc_folder_path, verbose_name='Right Rear Image')),
                ('right_front_image', models.ImageField(upload_to=workorder.models.this_wo_vc_folder_path, verbose_name='Right Front Image')),
                ('key_set_image', models.ImageField(upload_to=workorder.models.this_wo_vc_folder_path, verbose_name='Key Set Image')),
                ('boot_accessories_image', models.ImageField(upload_to=workorder.models.this_wo_vc_folder_path, verbose_name='Boot Accessories Image')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleConditionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_number', models.CharField(max_length=25, verbose_name='VIN')),
                ('registration_number', models.CharField(max_length=10, verbose_name='Registration Number')),
                ('mileage', models.IntegerField(verbose_name='Mileage')),
                ('fuel_level', models.CharField(choices=[('0/10', '0/10'), ('1/10', '1/10'), ('2/10', '2/10'), ('3/10', '3/10'), ('4/10', '4/10'), ('5/10', '5/10'), ('6/10', '6/10'), ('7/10', '7/10'), ('8/10', '8/10'), ('9/10', '9/10'), ('10/10', '10/10')], default='0/10', max_length=5, verbose_name='Fuel Level')),
                ('main_keys', models.CharField(choices=[('0', 0), ('1', 1), ('2', 2)], default='0', max_length=1, verbose_name='Main Keys')),
                ('transponder_keys', models.CharField(choices=[('0', 0), ('1', 1)], default='0', max_length=1, verbose_name='Transponder Keys')),
                ('registration_certificate', models.CharField(choices=[('NO', 'No'), ('ORIGINAL', 'Original'), ('PHOTOCOPY', 'Photocopy')], default='NO', max_length=10, verbose_name='Registration Certificate')),
                ('first_aid_kit', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3, verbose_name='First Aid Kit')),
                ('high_visibility_waistcoat', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3, verbose_name='High Visibility Waistcoat')),
                ('warning_triangle', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3, verbose_name='Warning Triangles')),
                ('luggage_net', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3, verbose_name='Luggage Net')),
                ('floor_mats', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3, verbose_name='Floor Mats')),
                ('rear_boot_rubber_mat', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3, verbose_name='Rear Boot Rubber Mat')),
                ('charging_cable_type2', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3, verbose_name='Charging Cable Type2')),
                ('charging_cable_schuko', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3, verbose_name='Charging Cable Schuko')),
                ('tyre_set', models.CharField(choices=[('SUMMER', 'Summer'), ('WINTER', 'Winter')], default='SUMMER', max_length=6, verbose_name='Tyre Set')),
                ('tow_bar', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3, verbose_name='Tow Bar')),
                ('proof_images', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorder.proofimagesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CarReceivingVCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_from', models.CharField(blank=True, max_length=50, null=True, verbose_name='Receiving From')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date and Time')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Location')),
                ('e_signature', models.ImageField(blank=True, null=True, upload_to=workorder.models.this_wo_car_receiving_vc_folder_path, verbose_name='E-Signature')),
                ('vehicle_condition', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorder.vehicleconditionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CarGivingVCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giving_to', models.CharField(blank=True, max_length=50, null=True, verbose_name='Giving To')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date and Time')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Location')),
                ('e_signature', models.ImageField(blank=True, null=True, upload_to=workorder.models.this_wo_car_giving_vc_folder_path, verbose_name='E-Signature')),
                ('vehicle_condition', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorder.vehicleconditionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrdersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(editable=False, max_length=10, unique=True, verbose_name='Work Order Number')),
                ('type', models.CharField(choices=[('CAR DELIVERY', 'Car Delivery'), ('CAR RETURN', 'Car Return'), ('PUD PICKUP', 'PUD Pickup'), ('PUD DROP', 'PUD Drop')], default='CAR DELIVERY', max_length=12, verbose_name='Work Order Type')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Work Order Created On')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DENIED', 'Denied'), ('ACCEPTED', 'Accepted'), ('IN PROCESS', 'In Process'), ('OUT FOR DELIVERY', 'Out For Delivery'), ('DELIVERY SUCCESSFUL', 'Delivery Successful'), ('DELIVERY UNSUCCESSFUL', 'Delivery Unsuccessful')], default='PENDING', max_length=21, verbose_name='Work Order Status')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery Date')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.carmodel', verbose_name='Car')),
                ('car_dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cardealer.cardealermodel', verbose_name='Car Dealer')),
                ('car_expenses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workordersmodel', to='workorder.carexpensesmodel', verbose_name='Car Expenses')),
                ('car_giving_vc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorder.cargivingvcmodel', verbose_name='Car Giving VC')),
                ('car_receiving_vc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workordersmodel', to='workorder.carreceivingvcmodel', verbose_name='Car Receiving VC')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customermodel', verbose_name='Customer')),
                ('delivery_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deliveryagent.deliveryagentmodel', verbose_name='Delivery Agent')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturer.manufacturermodel', verbose_name='Manufacturer')),
                ('overhead_expenses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorder.overheadexpensesmodel', verbose_name='Overhead Expenses')),
            ],
        ),
        migrations.AddField(
            model_name='vehicleconditionmodel',
            name='workorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorder.workordersmodel'),
        ),
        migrations.AddField(
            model_name='proofimagesmodel',
            name='workorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorder.workordersmodel'),
        ),
        migrations.AddField(
            model_name='overheadexpensesmodel',
            name='workorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorder.workordersmodel'),
        ),
        migrations.AddField(
            model_name='carreceivingvcmodel',
            name='workorder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorder.workordersmodel'),
        ),
        migrations.AddField(
            model_name='cargivingvcmodel',
            name='workorder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorder.workordersmodel'),
        ),
        migrations.AddField(
            model_name='carexpensesmodel',
            name='workorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorder.workordersmodel'),
        ),
    ]
