# Generated by Django 5.0.4 on 2024-04-12 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecondition', '0024_alter_carreceivingvcmodel_receiving_from_and_more'),
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workordersmodel',
            name='car_delivering_vc',
        ),
        migrations.AddField(
            model_name='workordersmodel',
            name='car_giving_vc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiclecondition.cargivingvcmodel', verbose_name='Car Giving VC'),
        ),
    ]
