# Generated by Django 5.0.4 on 2024-04-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0002_remove_workordersmodel_car_delivering_vc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordersmodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DENIED', 'Denied'), ('ACCEPTED', 'Accepted'), ('IN PROCESS', 'In Process'), ('OUT FOR DELIVERY', 'Out For Delivery'), ('DELIVERY SUCCESSFUL', 'Delivery Successful'), ('DELIVERY UNSUCCESSFUL', 'Delivery Unsuccessful')], default='PENDING', max_length=21, verbose_name='Work Order Status'),
        ),
        migrations.AlterField(
            model_name='workordersmodel',
            name='wo_number',
            field=models.CharField(editable=False, max_length=25, unique=True, verbose_name='Work Order Number'),
        ),
    ]
