# Generated by Django 5.0.4 on 2024-04-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0003_alter_workordersmodel_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workordersmodel',
            name='car',
        ),
        migrations.AddField(
            model_name='workordersmodel',
            name='car_vin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Car VIN'),
        ),
    ]
