# Generated by Django 5.0.4 on 2024-04-19 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryagent', '0001_initial'),
        ('workorder', '0004_remove_workordersmodel_car_workordersmodel_car_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordersmodel',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveryagent.deliveryagentmodel', verbose_name='Delivery Agent'),
        ),
    ]
