# Generated by Django 5.0.4 on 2024-04-19 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0007_alter_companymodel_name_and_more'),
        ('workorder', '0005_alter_workordersmodel_delivery_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordersmodel',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationery.personmodel', verbose_name='Delivery Agent'),
        ),
    ]
