# Generated by Django 5.0.4 on 2024-04-20 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryagent', '0001_initial'),
        ('workorder', '0006_alter_workordersmodel_delivery_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordersmodel',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deliveryagent.deliveryagentmodel', verbose_name='Delivery Agent'),
        ),
    ]
