# Generated by Django 5.0.4 on 2024-04-20 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealer', '0001_initial'),
        ('workorder', '0007_alter_workordersmodel_delivery_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordersmodel',
            name='car_dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cardealer.cardealermodel', verbose_name='Car Dealer'),
        ),
    ]
