# Generated by Django 5.0.4 on 2024-04-20 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0001_initial'),
        ('workorder', '0009_remove_workordersmodel_car_vin_workordersmodel_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordersmodel',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturer.manufacturermodel', verbose_name='Manufacturer'),
        ),
    ]
