# Generated by Django 5.0.4 on 2024-04-20 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('workorder', '0010_workordersmodel_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordersmodel',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customermodel', verbose_name='Customer'),
        ),
    ]
