# Generated by Django 5.0.4 on 2024-04-25 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stationery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True, verbose_name='Customer Number')),
                ('eligibility_check', models.BooleanField(blank=True, default=False, null=True, verbose_name='Eligibility Check')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationery.personmodel', verbose_name='Personal Info')),
            ],
        ),
    ]
