# Generated by Django 5.0.4 on 2024-05-13 23:40

import customer.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stationery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_number', models.CharField(editable=False, max_length=8, unique=True, verbose_name='Customer Number')),
                ('eligibility_check', models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=7, verbose_name='Eligibility Check')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Customer Created On')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationery.personmodel', verbose_name='Personal Info')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='PersonalDocumentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_pdf', models.FileField(upload_to=customer.models.this_cr_folder_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Passport Copy')),
                ('residence_permit_pdf', models.FileField(upload_to=customer.models.this_cr_folder_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Residence Permit Copy')),
                ('schufa_score_pdf', models.FileField(upload_to=customer.models.this_cr_folder_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Schufa Score Copy')),
                ('driving_license_pdf', models.FileField(upload_to=customer.models.this_cr_folder_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Driving License Copy')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customermodel')),
            ],
            options={
                'verbose_name': 'Personal Document',
                'verbose_name_plural': 'Personal Documents',
            },
        ),
        migrations.AddField(
            model_name='customermodel',
            name='personal_documents',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_documents', to='customer.personaldocumentsmodel', verbose_name='Personal Documents'),
        ),
    ]
