# Generated by Django 5.0.4 on 2024-04-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='eligibility_check',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Eligibility Check'),
        ),
    ]
