# Generated by Django 5.0.4 on 2024-04-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25, verbose_name='Brand')),
                ('model', models.CharField(max_length=25, verbose_name='Model')),
                ('color', models.CharField(choices=[('BLUE', 'Blue'), ('BLACK', 'Black')], max_length=5, verbose_name='Color')),
                ('vin_number', models.CharField(max_length=25, unique=True, verbose_name='VIN Number')),
                ('registration_number', models.CharField(max_length=10, verbose_name='Registration Number')),
                ('tuv_expire_date', models.DateField(verbose_name='Tuv Expire Date')),
            ],
        ),
    ]
