# Generated by Django 5.0.4 on 2024-04-05 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0002_personmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date of Birth'),
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationery.personmodel')),
            ],
        ),
    ]
