# Generated by Django 5.0.4 on 2024-04-05 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0003_personmodel_date_of_birth_employeemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='city',
            field=models.CharField(max_length=200, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='country',
            field=models.CharField(max_length=25, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='house',
            field=models.CharField(max_length=15, verbose_name='House'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='state',
            field=models.CharField(max_length=25, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='zip_code',
            field=models.CharField(max_length=10, verbose_name='ZIP'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='designation',
            field=models.CharField(max_length=100, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='email_address',
            field=models.EmailField(max_length=100, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Phone Number'),
        ),
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('registered_on', models.DateField(verbose_name='Registration Date')),
                ('registration_number', models.CharField(max_length=100, verbose_name='Registration Number')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationery.addressmodel')),
                ('employees', models.ManyToManyField(to='stationery.employeemodel', verbose_name='Employees')),
            ],
        ),
    ]
