# Generated by Django 5.0.4 on 2024-04-05 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0004_alter_addressmodel_city_alter_addressmodel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stationery.addressmodel'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, to='stationery.employeemodel', verbose_name='Employees'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stationery.personmodel'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stationery.addressmodel'),
        ),
    ]
