# Generated by Django 5.0.4 on 2024-04-14 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stationery', '0007_alter_companymodel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationery.personmodel', verbose_name='Personal Info')),
            ],
        ),
    ]
