# Generated by Django 5.0.4 on 2024-04-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecondition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleconditionmodel',
            name='fuel_level',
            field=models.IntegerField(choices=[('OPTION_ZERO', 0), ('OPTION_ONE', 1), ('OPTION_TWO', 2), ('OPTION_THREE', 3), ('OPTION_FOUR', 4), ('OPTION_FIVE', '5'), ('OPTION_SIX', 6), ('OPTION_SEVEN', 7), ('OPTION_EIGHT', 8), ('OPTION_NINE', 9), ('OPTION_TEN', 10)], default='OPTION_ZERO', verbose_name='Fuel Level'),
        ),
    ]
