# Generated by Django 5.0.4 on 2024-04-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecondition', '0002_alter_vehicleconditionmodel_fuel_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleconditionmodel',
            name='fuel_level',
            field=models.IntegerField(choices=[('OPTION_ZERO', '0/10'), ('OPTION_ONE', '1/10'), ('OPTION_TWO', '2/10'), ('OPTION_THREE', '3/10'), ('OPTION_FOUR', '4/10'), ('OPTION_FIVE', '5/10'), ('OPTION_SIX', '6/10'), ('OPTION_SEVEN', '7/10'), ('OPTION_EIGHT', '8/10'), ('OPTION_NINE', '9/10'), ('OPTION_TEN', '10/10')], default='OPTION_ZERO', verbose_name='Fuel Level'),
        ),
    ]
