# Generated by Django 5.0.4 on 2024-04-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecondition', '0004_alter_vehicleconditionmodel_fuel_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleconditionmodel',
            name='charging_cable_schuko',
        ),
        migrations.RemoveField(
            model_name='vehicleconditionmodel',
            name='charging_cable_type2',
        ),
        migrations.RemoveField(
            model_name='vehicleconditionmodel',
            name='first_aid_kit',
        ),
        migrations.RemoveField(
            model_name='vehicleconditionmodel',
            name='floor_mats',
        ),
        migrations.RemoveField(
            model_name='vehicleconditionmodel',
            name='high_visibility_waistcoat',
        ),
        migrations.RemoveField(
            model_name='vehicleconditionmodel',
            name='luggage_net',
        ),
        migrations.RemoveField(
            model_name='vehicleconditionmodel',
            name='main_keys',
        ),
        migrations.RemoveField(
            model_name='vehicleconditionmodel',
            name='rear_boot_rubber_mat',
        ),
        migrations.RemoveField(
            model_name='vehicleconditionmodel',
            name='registration_certificate',
        ),
        migrations.RemoveField(
            model_name='vehicleconditionmodel',
            name='tow_bar',
        ),
        migrations.RemoveField(
            model_name='vehicleconditionmodel',
            name='transponder_keys',
        ),
        migrations.RemoveField(
            model_name='vehicleconditionmodel',
            name='tyre_set',
        ),
        migrations.RemoveField(
            model_name='vehicleconditionmodel',
            name='warning_triangle',
        ),
        migrations.AlterField(
            model_name='vehicleconditionmodel',
            name='fuel_level',
            field=models.IntegerField(choices=[('OPTION_ONE', '1'), ('OPTION_TWO', '2')], default='OPTION_ZERO', verbose_name='Fuel Level'),
        ),
    ]
