# Generated by Django 5.0.4 on 2024-04-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecondition', '0005_remove_vehicleconditionmodel_charging_cable_schuko_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofimagesmodel',
            name='vin_number_image',
            field=models.ImageField(upload_to='media/workorder/%Y-%m-%d-%H-%M-%S/'),
        ),
    ]
