# Generated by Django 5.0.4 on 2024-04-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecondition', '0006_alter_proofimagesmodel_vin_number_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofimagesmodel',
            name='vin_number_image',
            field=models.ImageField(upload_to='workorder/%Y-%m-%d-%H-%M-%S/'),
        ),
    ]
