# Generated by Django 5.0.4 on 2024-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecondition', '0011_alter_vehicleconditionmodel_fuel_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleconditionmodel',
            name='main_keys',
            field=models.CharField(choices=[('0', 0), ('1', 1), ('2', 2)], default='0', max_length=15, verbose_name='Main Keys'),
        ),
    ]
