# Generated by Django 5.0.4 on 2024-04-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecondition', '0012_vehicleconditionmodel_main_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleconditionmodel',
            name='fuel_level',
            field=models.CharField(choices=[('0/10', '0/10'), ('1/10', '1/10'), ('2/10', '2/10'), ('3/10', '3/10'), ('4/10', '4/10'), ('5/10', '5/10'), ('6/10', '6/10'), ('7/10', '7/10'), ('8/10', '8/10'), ('9/10', '9/10'), ('10/10', '10/10')], default='0/10', max_length=5, verbose_name='Fuel Level'),
        ),
        migrations.AlterField(
            model_name='vehicleconditionmodel',
            name='main_keys',
            field=models.CharField(choices=[('0', 0), ('1', 1), ('2', 2)], default='0', max_length=1, verbose_name='Main Keys'),
        ),
    ]
