# Generated by Django 5.0.4 on 2024-04-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecondition', '0013_alter_vehicleconditionmodel_fuel_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleconditionmodel',
            name='registration_certificate',
            field=models.CharField(choices=[('NO', 'No'), ('ORIGINAL', 'Original'), ('PHOTOCOPY', 'Photocopy')], default='NO', max_length=10, verbose_name='Registration Certificate'),
        ),
        migrations.AddField(
            model_name='vehicleconditionmodel',
            name='transponder_keys',
            field=models.CharField(choices=[('0', 0), ('1', 1)], default='0', max_length=1, verbose_name='Transponder Keys'),
        ),
    ]
