# Generated by Django 5.0.4 on 2024-04-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecondition', '0014_vehicleconditionmodel_registration_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleconditionmodel',
            name='charging_cable_schuko',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3, verbose_name='Charging Cable Schuko'),
        ),
        migrations.AddField(
            model_name='vehicleconditionmodel',
            name='charging_cable_type2',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3, verbose_name='Charging Cable Type2'),
        ),
        migrations.AddField(
            model_name='vehicleconditionmodel',
            name='first_aid_kit',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3, verbose_name='First Aid Kit'),
        ),
        migrations.AddField(
            model_name='vehicleconditionmodel',
            name='floor_mats',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3, verbose_name='Floor Mats'),
        ),
        migrations.AddField(
            model_name='vehicleconditionmodel',
            name='high_visibility_waistcoat',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3, verbose_name='High Visibility Waistcoat'),
        ),
        migrations.AddField(
            model_name='vehicleconditionmodel',
            name='luggage_net',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3, verbose_name='Luggage Net'),
        ),
        migrations.AddField(
            model_name='vehicleconditionmodel',
            name='rear_boot_rubber_mat',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3, verbose_name='Rear Boot Rubber Mat'),
        ),
        migrations.AddField(
            model_name='vehicleconditionmodel',
            name='tow_bar',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3, verbose_name='Tow Bar'),
        ),
        migrations.AddField(
            model_name='vehicleconditionmodel',
            name='tyre_set',
            field=models.CharField(choices=[('SUMMER', 'Summer'), ('WINTER', 'Winter')], default='SUMMER', max_length=6, verbose_name='Tyre Set'),
        ),
        migrations.AddField(
            model_name='vehicleconditionmodel',
            name='warning_triangle',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=3, verbose_name='Warning Triangles'),
        ),
        migrations.AlterField(
            model_name='vehicleconditionmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created on'),
        ),
    ]
