# Generated by Django 5.0.4 on 2024-04-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecondition', '0015_vehicleconditionmodel_charging_cable_schuko_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofimagesmodel',
            name='boot_accessories_image',
            field=models.ImageField(blank=True, null=True, upload_to='workorder/%Y-%m-%d-%H-%M-%S/', verbose_name='Boot Accessories Image'),
        ),
        migrations.AddField(
            model_name='proofimagesmodel',
            name='dashboard_image',
            field=models.ImageField(blank=True, null=True, upload_to='workorder/%Y-%m-%d-%H-%M-%S/', verbose_name='Dashboard Image'),
        ),
        migrations.AddField(
            model_name='proofimagesmodel',
            name='emission_sticker_image',
            field=models.ImageField(blank=True, null=True, upload_to='workorder/%Y-%m-%d-%H-%M-%S/', verbose_name='Emission Sticker Image'),
        ),
        migrations.AddField(
            model_name='proofimagesmodel',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='workorder/%Y-%m-%d-%H-%M-%S/', verbose_name='Front Image'),
        ),
        migrations.AddField(
            model_name='proofimagesmodel',
            name='key_set_image',
            field=models.ImageField(blank=True, null=True, upload_to='workorder/%Y-%m-%d-%H-%M-%S/', verbose_name='Key Set Image'),
        ),
        migrations.AddField(
            model_name='proofimagesmodel',
            name='left_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='workorder/%Y-%m-%d-%H-%M-%S/', verbose_name='Left Front Image'),
        ),
        migrations.AddField(
            model_name='proofimagesmodel',
            name='left_rear_image',
            field=models.ImageField(blank=True, null=True, upload_to='workorder/%Y-%m-%d-%H-%M-%S/', verbose_name='Left Rear Image'),
        ),
        migrations.AddField(
            model_name='proofimagesmodel',
            name='license_plate_image',
            field=models.ImageField(blank=True, null=True, upload_to='workorder/%Y-%m-%d-%H-%M-%S/', verbose_name='License Plate Image'),
        ),
        migrations.AddField(
            model_name='proofimagesmodel',
            name='rear_image',
            field=models.ImageField(blank=True, null=True, upload_to='workorder/%Y-%m-%d-%H-%M-%S/', verbose_name='Rear Image'),
        ),
        migrations.AddField(
            model_name='proofimagesmodel',
            name='registration_certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='workorder/%Y-%m-%d-%H-%M-%S/', verbose_name='Registration Certificate Image'),
        ),
        migrations.AddField(
            model_name='proofimagesmodel',
            name='right_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='workorder/%Y-%m-%d-%H-%M-%S/', verbose_name='Right Front Image'),
        ),
        migrations.AddField(
            model_name='proofimagesmodel',
            name='right_rear_image',
            field=models.ImageField(blank=True, null=True, upload_to='workorder/%Y-%m-%d-%H-%M-%S/', verbose_name='Right Rear Image'),
        ),
        migrations.AlterField(
            model_name='proofimagesmodel',
            name='vin_number_image',
            field=models.ImageField(blank=True, null=True, upload_to='workorder/%Y-%m-%d-%H-%M-%S/', verbose_name='VIN Image'),
        ),
    ]
