# Generated by Django 5.0.4 on 2024-04-08 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecondition', '0016_proofimagesmodel_boot_accessories_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleconditionmodel',
            name='proof_images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiclecondition.proofimagesmodel'),
        ),
    ]
