# Generated by Django 5.0.4 on 2024-04-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecondition', '0019_cardeliveringvcmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleconditionmodel',
            name='created_on',
        ),
    ]
