# Generated by Django 5.0.4 on 2024-04-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecondition', '0020_remove_vehicleconditionmodel_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardeliveringvcmodel',
            name='date_and_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='carreceivingvcmodel',
            name='date_and_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date and Time'),
        ),
    ]
