# Generated by Django 5.0.4 on 2024-04-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecondition', '0021_alter_cardeliveringvcmodel_date_and_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardeliveringvcmodel',
            old_name='date_and_time',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='carreceivingvcmodel',
            old_name='date_and_time',
            new_name='created_on',
        ),
    ]
