# Generated by Django 5.0.4 on 2024-04-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecondition', '0022_rename_date_and_time_cardeliveringvcmodel_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardeliveringvcmodel',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='carreceivingvcmodel',
            name='signature',
        ),
        migrations.AddField(
            model_name='cardeliveringvcmodel',
            name='e_signature',
            field=models.ImageField(blank=True, null=True, upload_to='workorder/%Y-%m-%d-%H-%M-%S/', verbose_name='E-Signature'),
        ),
        migrations.AddField(
            model_name='carreceivingvcmodel',
            name='e_signature',
            field=models.ImageField(blank=True, null=True, upload_to='workorder/%Y-%m-%d-%H-%M-%S/', verbose_name='E-Signature'),
        ),
    ]
