# Generated by Django 5.0.4 on 2024-04-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclecondition', '0024_alter_carreceivingvcmodel_receiving_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreceivingvcmodel',
            name='wo_number',
            field=models.CharField(editable=False, max_length=25, unique=True, verbose_name='Work Order Number'),
        ),
    ]
